name: Docker Image CI

on:
  push:
    branches: [ Gustavo-Zamboni ]
  pull_request:
    branches: [ Gustavo-Zamboni ]

  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker

    - name: Run within Docker
      run: docker run --name teste -d -p 8000:8000 python-docker
    
      
    - name: sleep
      run: sleep 5s
      
    - name: logs
      run: docker logs teste
      
    - run: curl localhost:8000

    - name: Uptime Action
      # You may pin to the exact commit or the version.
      # uses: srt32/uptime@958231f4d95c117f08eb0fc70907e80d0dfedf2b
      uses: srt32/uptime@v0.2.1
      with:
        # which url to hit
        url-to-hit: "https:localhost:8000/"
        # which http response statuses are expected
        expected-statuses: "200,400"
