name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker:$(date +%s)

    - name: Run within Docker
      # You may pin to the exact commit or the version.
      # uses: mosteo-actions/docker-run@1e8c2ac951679fbb21485cbb4eed9e39246ad823
      uses: mosteo-actions/docker-run@v1
      with:
        # A dockerhub image
        image: python-docker:$(date +%s) 
        # Host dir to map into the container
        host-dir: ${{ github.workspace }}
        # Guest dir that will overlay host-dir, and be used as working directory
        guest-dir: ${{ github.workspace }}
        
    - name: HTTP Status
      # You may pin to the exact commit or the version.
      # uses: lakuapik/gh-actions-http-status@705c34b4307b8a0354a431b75bb5910b6562dd20
      uses: lakuapik/gh-actions-http-status@v1
      with:
        # List website urls in JSON 
        sites: '["localhost:8000/", "localhost:8000/erro"]'
        # List expected HTTP status codes in JSON
        expected: '[200, 400]'
