name: Docker Image CI

on:
  push:
    branches: [ Gustavo-Zamboni ]
  pull_request:
    branches: [ Gustavo-Zamboni ]

  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-docker

    - name: Run within Docker
      run: docker run --name teste -d -p 8000:8000 python-docker
    
      
    - name: sleep
      run: sleep 5s
      
    - name: logs
      run: docker logs teste
      
    - run: curl localhost:8000

    - name: Http_Status_Code_200
      id: Http_Status_Code_200
      run: echo "::set-output name=status::$(curl -o /dev/null -s -w "%{http_code}\n" localhost:8000/)"
    - uses: nick-invision/assert-action@v1
      with:
        expected: 200
        actual: ${{ steps.Http_Status_Code_200.outputs.status }}
        
    - name: Http_Status_Code_400
      id: Http_Status_Code_400
      run: echo "::set-output name=status::$(curl -o /dev/null -s -w "%{http_code}\n" localhost:8000/erro)"
    - uses: nick-invision/assert-action@v1
      with:
        expected: 400
        actual: ${{ steps.Http_Status_Code_400.outputs.status }}
      
